---
extends: default
rules:
  document-start: disable
  line-length: disable
  new-line-at-end-of-file:
    level: warning
  new-lines:
    level: warning
  trailing-spaces:
    level: warning
  brackets:
    level: warning
  indentation:
    level: warning
