name: Check AWS secrets

on:
  workflow_call:
  workflow_dispatch:

env:
  AWS_ACCESS_KEY_ID: "${{ secrets.AWS_ACCESS_KEY_ID }}"
  AWS_SECRET_ACCESS_KEY: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"

jobs:
  aws-check-secrets:
    runs-on: ubuntu-latest
    outputs:
      is_AWS_ACCESS_KEY_ID_set: ${{ steps.checksecret.outputs.is_AWS_ACCESS_KEY_ID_set }}
      is_AWS_SECRET_ACCESS_KEY_set: ${{ steps.checksecret.outputs.is_AWS_SECRET_ACCESS_KEY_set }}
    steps:
      - name: Check AWS secret set
        id: checksecret
        run: |
          set -x
          echo "is_AWS_ACCESS_KEY_ID_set=${{ env.AWS_ACCESS_KEY_ID != '' }}" >> $GITHUB_OUTPUT
          echo "is_AWS_SECRET_ACCESS_KEY_set=${{ env.AWS_SECRET_ACCESS_KEY != '' }}" >> $GITHUB_OUTPUT
