name: Docker Build AWS ECR

on:
  workflow_dispatch:
  push:

jobs:
  check-aws-secrets:
    uses: ./.github/workflows/aws_check_secrets.yml

  ecr-docker-build:
    name: ECR Docker Build
    uses: ./.github/workflows/reusable-ecr-docker-build.yaml
    needs: [check-aws-secrets]
    secrets: inherit
    if: |
      needs.check-aws-secrets.outputs.is_AWS_ACCESS_KEY_ID_set == 'true' &&
      needs.check-aws-secrets.outputs.is_AWS_SECRET_ACCESS_KEY_set == 'true'
    with:
      ### REQUIRED
      ### if docker to push.
      ecr-enable: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }}

      ### OPTIONALS
      ### path to where docker should copy files into image
      ### defaults to root of repository (.)
      # context: .

  gh-debug:
    uses: ./.github/workflows/gh-debug.yml
