name: Docker Build AWS ECR

on:
  workflow_dispatch:
  push:

jobs:
  call-ecr-docker-build:
    name: Call Docker Build
    uses: ./.github/workflows/reusable-ecr-docker-build.yaml

    permissions:
      contents: read

    secrets:

      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    with:

      ### REQUIRED
      ### if docker to push.
      ecr-enable: github.ref == 'refs/heads/main' && github.event_name == 'push'

      ### path to where docker should copy files into image
      ### defaults to root of repository (.)
      # context: .
