# https://docs.github.com/en/actions/creating-actions/creating-a-composite-action
name: Composite

on:
  workflow_dispatch:
  push:

jobs:
  composite_job:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./composite-action/hello
        id: hello
        with:
          who-to-greet: ${{ github.repository_owner }}
      - run: echo random-number ${{ steps.hello.outputs.random-number }}

  gh-debug:
    if: github.ref != 'refs/heads/main'
    uses: ./.github/workflows/gh-debug.yml
    needs: [composite_job]
