name: composite_hello

on:
  workflow_dispatch:
  push:

jobs:
  composite_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./composite-action/hello
        id: foo
        with:
          who-to-greet: ${{ github.repository_owner }}
      - run: echo random-number ${{ steps.foo.outputs.random-number }}
        shell: bash
