name: docker-action

on:
  workflow_dispatch:
  push:

jobs:
  docker_action_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v4
      - name: Hello world action step
        id: hello
        #uses: actions/hello-world-docker-actionv2
        uses: ./docker-action
        with:
          who-to-greet: '${{ github.repository_owner }}'
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"

  gh-debug:
    if: github.ref != 'refs/heads/main'
    uses: ./.github/workflows/gh-debug.yml
