# https://docs.github.com/en/rest/repos/repos#create-a-repository-dispatch-event
# Note: This event will only trigger a workflow run if the workflow file is on the default branch.

name: failure-webhook

on:
  repository_dispatch:
    types: [test_result] # limited to 100 characters

jobs:
  run_if_failure:
    if: ${{ !github.event.client_payload.passed }}
    runs-on: ubuntu-latest
    steps:
      - env:
          MESSAGE: ${{ github.event.client_payload.message }}
        run: echo $MESSAGE

  echo_json_job:
    runs-on: ubuntu-latest
    steps:
      - name: Dump json
        run: echo "$JSON_DATA"
        shell: bash
        env:
          JSON_DATA: ${{ toJson(repository_dispatch) }}
