# https://raw.githubusercontent.com/brennerm/github-actions-pr-close-showcase/master/.github/workflows/pr-close.yml
name: Close PR

on:
  pull_request:
    types:
      - closed

jobs:
  merge_job:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "PR ${{ github.event.number }} has been merged"

  close_job:
    if: github.event.pull_request.merged == false
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "PR ${{ github.event.number }} has been closed without being merged"

  gh-debug:
    uses: ./.github/workflows/gh-debug.yml
