name: Build and deploy to AWS ECR

on:
  # Reusable workflow
  workflow_call:
    inputs:
      ecr-enable:
        description: "Build and push to ECR?"
        required: false
        default: true
        type: boolean
      context:
        description: "Docker context path to start build from? (.)"
        required: false
        type: string
        default: .
      aws_region:
        description: "What AWS region to use (eu-west-1)"
        required: false
        type: string
        default: eu-west-1
      container_repository:
        description: "The name of container repository"
        required: false
        type: string
        default: |
          ${{ github.repository }}
      image_tag:
        description: "Tags for the container (SHA)"
        required: false
        type: string
        default: |
          ${{ github.sha }}
    # https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-envvars.html
    secrets:
      aws-access-key-id:
        description: AWS secret id
        required: true
      aws-secret-access-key:
        description: AWS secret key
        required: true

    outputs:
      image:
        description: "Get full path of the image"
        value: ${{ jobs.build-image.outputs.image }}

permissions:
  contents: read

jobs:
  build-and-push:
    name: AWS ECR Build and push
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.ecr-enable }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ inputs.aws_region }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: ${{ inputs.container_repository }}
          IMAGE_TAG: ${{ inputs.image_tag }}
        run: |
          docker build -t $ECR_REGISTRY/$REPOSITORY:$IMAGE_TAG ${{ inputs.context }}
          docker push $ECR_REGISTRY/$REPOSITORY:$IMAGE_TAG
          echo '::echo::on'
          echo "image=$ECR_REGISTRY/$REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT
